# Generated by Django 2.1.7 on 2019-03-31 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_frontendusers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2019, 3, 31, 11, 5, 41, 603341, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FrontendUsers')),
            ],
        ),
        migrations.CreateModel(
            name='Jit_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='jit.Jit')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jit.Jit')),
            ],
        ),
        migrations.CreateModel(
            name='Jit_Likedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jit.Jit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FrontendUsers')),
            ],
        ),
    ]
