# Generated by Django 2.1.7 on 2019-03-31 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 14, 12, 36, 958432, tzinfo=utc)),
        ),
    ]
