# Generated by Django 2.1.7 on 2019-03-31 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0002_auto_20190331_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='jit',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 18, 54, 11, 164659, tzinfo=utc)),
        ),
    ]
