# Generated by Django 2.1.7 on 2019-04-06 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0004_auto_20190406_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 11, 31, 13, 393256, tzinfo=utc)),
        ),
    ]
