# Generated by Django 2.1.7 on 2019-04-12 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0013_auto_20190411_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 13, 27, 3, 302393, tzinfo=utc)),
        ),
    ]
