# Generated by Django 2.1.7 on 2019-03-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190331_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendusers',
            name='name',
        ),
    ]
