# Generated by Django 2.1.7 on 2019-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendusers',
            name='avatar',
            field=models.ImageField(upload_to='media/media'),
        ),
    ]
