# Generated by Django 2.1.7 on 2019-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190409_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendusers',
            name='avatar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
