# Generated by Django 2.1.7 on 2019-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190411_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendusers',
            name='avatar',
            field=models.ImageField(upload_to='media/media'),
        ),
    ]
