# Generated by Django 2.1.7 on 2019-04-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190412_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendusers',
            name='avatar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
